// HopProxy 隧道请求上下文 wire schema。
//
// 单个请求的全部上下文（目标地址、代理策略、限流配置、日志关联）打包为
// 一个 protobuf 消息，base64url 编码后放入 X-Hop-Ctx 请求头。
// 选 protobuf 而非 gob 的原因：gob 每次新流编码都会重发类型描述（struct 名 +
// 字段名 + 字段类型，本消息实测 234B，占单次编码 51%）；protobuf 用字段号
// 代替字段名，实测体积 611B → 283B（base64 后）。
//
// 兼容性约束（与 gob 版一致的"直接切换、两端同时升级"策略）：
//   - 字段号一旦发布不得变更/复用；新增字段只能用未使用过的号
//   - 删除字段时保留 reserved（避免字段号被误复用）
//   - 修改字段类型属于破坏性变更，需要提升 version 字段
//
// 重新生成（改动本文件后）：
//   protoc --plugin=protoc-gen-go=$(which protoc-gen-go) \
//     --go_out=. --go_opt=paths=source_relative pkg/tunnel/tunnelpb/hopctx.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: pkg/tunnel/tunnelpb/hopctx.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HopContext 全链路请求上下文（wire 表示）。
// 发起端构造，各跳 PopHopContext（读即 pop）/ ApplyTo（转发即重编码）。
type HopContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                              // 协议版本（当前 1；不匹配时明确报错提示未同步升级）
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                          // 全链路请求关联 ID（入口生成，各跳透传，#62）
	Subdomain        string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`                                           // 请求子域名（日志关联）
	AppId            int64                  `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                     // 命中的应用 ID（日志关联）
	OriginalPath     string                 `protobuf:"bytes,5,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`                 // 路径改写前的原始路径（#53）
	TargetUrl        string                 `protobuf:"bytes,6,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`                          // 目标地址（带外传递，不占用请求行）
	ProxyType        string                 `protobuf:"bytes,7,opt,name=proxy_type,json=proxyType,proto3" json:"proxy_type,omitempty"`                          // 出站代理类型（peer/socks5/shadowsocks）
	ProxyAddress     string                 `protobuf:"bytes,8,opt,name=proxy_address,json=proxyAddress,proto3" json:"proxy_address,omitempty"`                 // 出站代理地址
	PeerSecret       string                 `protobuf:"bytes,9,opt,name=peer_secret,json=peerSecret,proto3" json:"peer_secret,omitempty"`                       // peer 认证密钥（目标客户端的 peer_secret）
	AgentKeyUuid     string                 `protobuf:"bytes,10,opt,name=agent_key_uuid,json=agentKeyUuid,proto3" json:"agent_key_uuid,omitempty"`              // agent Transport 密钥 UUID（#52）
	LimitsSet        bool                   `protobuf:"varint,11,opt,name=limits_set,json=limitsSet,proto3" json:"limits_set,omitempty"`                        // 限流三件套是否已由发起端解析填充（#47）
	MaxBodySize      int64                  `protobuf:"varint,12,opt,name=max_body_size,json=maxBodySize,proto3" json:"max_body_size,omitempty"`                // 请求体/WS 消息上限（字节，0=不限）
	ConnectTimeoutMs int64                  `protobuf:"varint,13,opt,name=connect_timeout_ms,json=connectTimeoutMs,proto3" json:"connect_timeout_ms,omitempty"` // 连接目标超时（毫秒，0=不限）
	ReadTimeoutMs    int64                  `protobuf:"varint,14,opt,name=read_timeout_ms,json=readTimeoutMs,proto3" json:"read_timeout_ms,omitempty"`          // 读响应超时（毫秒，0=不限）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HopContext) Reset() {
	*x = HopContext{}
	mi := &file_pkg_tunnel_tunnelpb_hopctx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopContext) ProtoMessage() {}

func (x *HopContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_tunnelpb_hopctx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopContext.ProtoReflect.Descriptor instead.
func (*HopContext) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescGZIP(), []int{0}
}

func (x *HopContext) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HopContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HopContext) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *HopContext) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *HopContext) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *HopContext) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *HopContext) GetProxyType() string {
	if x != nil {
		return x.ProxyType
	}
	return ""
}

func (x *HopContext) GetProxyAddress() string {
	if x != nil {
		return x.ProxyAddress
	}
	return ""
}

func (x *HopContext) GetPeerSecret() string {
	if x != nil {
		return x.PeerSecret
	}
	return ""
}

func (x *HopContext) GetAgentKeyUuid() string {
	if x != nil {
		return x.AgentKeyUuid
	}
	return ""
}

func (x *HopContext) GetLimitsSet() bool {
	if x != nil {
		return x.LimitsSet
	}
	return false
}

func (x *HopContext) GetMaxBodySize() int64 {
	if x != nil {
		return x.MaxBodySize
	}
	return 0
}

func (x *HopContext) GetConnectTimeoutMs() int64 {
	if x != nil {
		return x.ConnectTimeoutMs
	}
	return 0
}

func (x *HopContext) GetReadTimeoutMs() int64 {
	if x != nil {
		return x.ReadTimeoutMs
	}
	return 0
}

var File_pkg_tunnel_tunnelpb_hopctx_proto protoreflect.FileDescriptor

const file_pkg_tunnel_tunnelpb_hopctx_proto_rawDesc = "" +
	"\n" +
	" pkg/tunnel/tunnelpb/hopctx.proto\x12\x12hopproxy.tunnel.v1\"\xe2\x03\n" +
	"\n" +
	"HopContext\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appId\x12#\n" +
	"\roriginal_path\x18\x05 \x01(\tR\foriginalPath\x12\x1d\n" +
	"\n" +
	"target_url\x18\x06 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"proxy_type\x18\a \x01(\tR\tproxyType\x12#\n" +
	"\rproxy_address\x18\b \x01(\tR\fproxyAddress\x12\x1f\n" +
	"\vpeer_secret\x18\t \x01(\tR\n" +
	"peerSecret\x12$\n" +
	"\x0eagent_key_uuid\x18\n" +
	" \x01(\tR\fagentKeyUuid\x12\x1d\n" +
	"\n" +
	"limits_set\x18\v \x01(\bR\tlimitsSet\x12\"\n" +
	"\rmax_body_size\x18\f \x01(\x03R\vmaxBodySize\x12,\n" +
	"\x12connect_timeout_ms\x18\r \x01(\x03R\x10connectTimeoutMs\x12&\n" +
	"\x0fread_timeout_ms\x18\x0e \x01(\x03R\rreadTimeoutMsB0Z.github.com/robin/hop-proxy/pkg/tunnel/tunnelpbb\x06proto3"

var (
	file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescOnce sync.Once
	file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescData []byte
)

func file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescGZIP() []byte {
	file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescOnce.Do(func() {
		file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tunnel_tunnelpb_hopctx_proto_rawDesc), len(file_pkg_tunnel_tunnelpb_hopctx_proto_rawDesc)))
	})
	return file_pkg_tunnel_tunnelpb_hopctx_proto_rawDescData
}

var file_pkg_tunnel_tunnelpb_hopctx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_tunnel_tunnelpb_hopctx_proto_goTypes = []any{
	(*HopContext)(nil), // 0: hopproxy.tunnel.v1.HopContext
}
var file_pkg_tunnel_tunnelpb_hopctx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_tunnel_tunnelpb_hopctx_proto_init() }
func file_pkg_tunnel_tunnelpb_hopctx_proto_init() {
	if File_pkg_tunnel_tunnelpb_hopctx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tunnel_tunnelpb_hopctx_proto_rawDesc), len(file_pkg_tunnel_tunnelpb_hopctx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_tunnel_tunnelpb_hopctx_proto_goTypes,
		DependencyIndexes: file_pkg_tunnel_tunnelpb_hopctx_proto_depIdxs,
		MessageInfos:      file_pkg_tunnel_tunnelpb_hopctx_proto_msgTypes,
	}.Build()
	File_pkg_tunnel_tunnelpb_hopctx_proto = out.File
	file_pkg_tunnel_tunnelpb_hopctx_proto_goTypes = nil
	file_pkg_tunnel_tunnelpb_hopctx_proto_depIdxs = nil
}
